### Python para cálculo numerico

#### Numpy

biblioteca Numpy é a base da maior parte dos algoritmos utilizados nesses estudos

##### Arrays

In [1]:
# importação Numpy para calculos numericos
import numpy as np

A = np.array( [[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

B = np.array([[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]])

# operação entre matrizes, outra opção é numpy.dot()
C = A@B

# visualização da matriz resultado
print(C)

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


##### Manipulações e funções internas

In [2]:
# um range de valores do 0-14
a = np.arange(15)

print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [3]:
# array 1, 15
a = np.arange(15)
print(a)

# array 3 linhas, 5 colunas
a = a.reshape(3, 5)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
a = np.arange(64)
a = a.reshape(16, 4)

print(a)

# formato 16 linhas, 4 colunas
print(a.shape)

# quantidade de valores
print(a.size)

# quantidade de linhas
print(len(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]
 [48 49 50 51]
 [52 53 54 55]
 [56 57 58 59]
 [60 61 62 63]]
(16, 4)
64
16


In [5]:
a = np.arange(15)
print(f'a =\n {a}')

# usamos o \n para quebra de linha
a = a.reshape(3, 5)
print(f'a =\n {a}')

# f-strings facilita a formação
b = a[1:3, 3:5]
print(f'b =\ {b}')

a =
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
a =
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
b =\ [[ 8  9]
 [13 14]]


#### Matplotlib

##### Plotagem 2D

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# 35 valores entre - pi e p
x = np.linspace(-np.pi, np.pi, 35)

#### Scipy

### FIM.